# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Run the command to execute your JavaScript file
CMD ["node", "0-javascript_is_amazing.js"]

